### T2_2024 - NPPE 1 (Pre-Processing)

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iitmbs-mlp-nppe1/NPPE1_ModelBuilding1.csv
/kaggle/input/iitmbs-mlp-nppe1/NPPE1_Preprocessing1.csv
/kaggle/input/iitmbs-mlp-nppe1/NPPE1_Preprocessing3.csv
/kaggle/input/iitmbs-mlp-nppe1/NPPE1_ModelBuilding3.csv

### Dataset Description
Following is a description of different columns in the dataset.

- **CRIM**: per capita crime rate in the vicinity
- **ZN**: amount of residential land reserved in the vicinity.
- **INDUS**: proportion of industrial land reserved nearby (in square kilometers)
- **RIVERSIDE**: If the boundary faces river side (= 1 if tract bounds river; 0 otherwise)
- **POLINDEX**: polution index
- **RM**: number of rooms in the house.
- **AGE**: Age of the property in years.
- **DIS**: weighted distances to the major economic centres (in kilometers)
- **HIGHWAYCOUNT**: Number of highways within 5 KM of distance.
- **TAX**: full-value property-tax rate per 1 lac.
- **PTRATIO**: student-teacher ratio in the vicinity.
- **IMM**: Immigration index in the vicinity.
- **BPL**: % of below poverty line population in the vicinity.
- **PRICE**: Price of the home in lacs, this is the **target** column.

### Q1: Which dataset are you using for this exam?
- [x] NPPE1_Preprocessing1.csv
- [ ] NPPE1_Preprocessing2.csv
- [ ] NPPE1_Preprocessing3.csv
- [ ] NPPE1_Preprocessing4.csv

In [2]:
df = pd.read_csv("/kaggle/input/iitmbs-mlp-nppe1/NPPE1_Preprocessing1.csv")
df.head()

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,1.026769,1.429034,7.851300,1.134216,6.0,42.0,5.251911,5,279.201277,20.689586,398.811960,10.461456,22.991633,NO
1,0.848089,0.255543,6.263434,1.245993,7.0,63.0,4.305546,8,307.444529,17.465398,377.153649,11.619690,24.551055,NO
2,10.925905,0.441022,18.322960,2.824833,8.0,-2.0,2.409495,25,666.492973,20.351601,387.061355,19.366070,15.875346,NO
3,0.559027,1.041175,11.114920,0.794952,6.0,9.0,6.898669,4,305.514181,19.787314,391.778647,6.206820,23.007756,NO
4,0.905063,81.167963,3.673369,1.029030,8.0,20.0,10.246463,1,315.913960,17.360439,395.833166,10.827105,21.503177,NO

### Q2: How many samples are there in the dataset?
- [x] 4000
- [ ] 5000
- [ ] 6000
- [ ] 7000

In [3]:
df.shape

(4000, 14)

### Q3: What is the average house price (in lacs)?

In [4]:
df["PRICE"].mean()

24.355923220694248

### Q4: How many houses have 5 or more rooms?
- [x] 3953
- [ ] 3921
- [ ] 3896
- [ ] 3932
- [ ] 3925
- [ ] None of these

In [5]:
df[df["RM"] >= 5].shape

(3953, 14)

### Q5: What is the average price of the top 10 most expensive houses (in lacs)?

In [6]:
top_10 = df["PRICE"].nlargest(10)
top_10.mean()

52.36590175716407

### Q6: What is the total number of missing or unknown values in the number of rooms feature?

(Hint: carefully look at the values the feature takes and find out implausible value.)
- [x] 40
- [ ] 71
- [ ] 99
- [ ] 61
- [ ] 68
- [ ] None of these

In [7]:
df["RM"].isnull().sum()

0

In [8]:
df["RM"].unique()

array([ 6.,  7.,  8.,  9., 10., -1.,  5.,  4., 11.])

In [9]:
# df["RM"] = df["RM"].replace(-1, np.nan)

In [10]:
df["RM"].value_counts()[-1]

40

### Q7: What is the total number of missing or unknown values in the age feature?

(Hint: carefully look at the values the feature takes and find out implausible value.)
- [x] 50
- [ ] 83
- [ ] 74
- [ ] 64
- [ ] 59
- [ ] None of these

In [11]:
df["AGE"].isnull().sum()

0

In [12]:
df["AGE"].unique()

array([ 42.,  63.,  -2.,   9.,  20.,  95.,  35.,  97.,  36.,  78.,  99.,
        96.,  19.,  73.,  86.,  37.,  76.,  50.,  32.,  92., 101.,   8.,
        94.,  84.,  47.,  43.,  65.,  46.,  59.,  74.,  93.,  80.,  98.,
       102.,  56., 100.,  89.,  53.,  18.,  71.,  62.,  83.,  66.,   7.,
        77.,  91.,  90.,  58.,  57.,  60.,  87.,  75.,  34.,  85.,  48.,
        33.,  38.,  30.,  23.,  55.,  11.,  14.,  45.,  41.,  88.,  16.,
        12.,  79.,  67.,  39.,  49.,  61.,  70.,  54.,  10.,  22.,  72.,
        15.,  51.,  81.,  31.,  52.,  44.,  28.,  17.,  40.,  29.,  69.,
        64.,  24.,  82.,  26.,  68.,  27.,  13., 103.,  21.,  25.,   6.,
         5.,   3.,   4.])

In [13]:
# df["AGE"] = df["AGE"].replace(-2, np.nan)

In [14]:
df["AGE"].value_counts()[-2]

50

### Q8: What is the total number of missing or unknown values in the RIVERSIDE feature?

(Hint: carefully look at the values the feature takes and find out implausible value.)
- [x] 88
- [ ] 101
- [ ] 56
- [ ] 62
- [ ] 80
- [ ] None of these

In [15]:
df["RIVERSIDE"].isnull().sum()

0

In [16]:
df["RIVERSIDE"].unique()

array(['NO', 'UNKNOWN', 'YES'], dtype=object)

In [17]:
# df["RIVERSIDE"] = df["RIVERSIDE"].replace("UNKNOWN", np.nan)

In [18]:
df["RIVERSIDE"].value_counts()["UNKNOWN"]

88

### Q9: How many houses are on riverside and were built within the last 50 years (i.e. a house 50 years old or younger)? For this question, ignore the rows that have missing values in either riverside feature or age feature.
- [x] 44
- [ ] 42
- [ ] 52
- [ ] 43
- [ ] 37
- [ ] None of these

In [19]:
df[(df["RIVERSIDE"]=="YES") & (df["AGE"] <= 50) & (df["AGE"]!=-2)].shape

(44, 14)

### Q10: How many houses are near to exactly 6, 7 or 8 highways (all three inclusive)?
- [x] 1211
- [ ] 1174
- [ ] 1234
- [ ] 938
- [ ] 1209
- [ ] None of these

In [20]:
df[df["HIGHWAYCOUNT"].isin((6, 7, 8))].shape

(1211, 14)

Create a column 'CATEGORY' and divide the houses in categories as following:

- Category 1: house price <10 lacs
- Category 2: 10 lacs <= house price <20 lacs
- Category 3: 20 lacs <= house price <30 lacs
- Category 4: 30 lacs <= house price <40 lacs
- Category 5: house price >=40 lacs

### Q11: Which category has the highest number of records?
- [ ] 1
- [ ] 2
- [x] 3
- [ ] 4
- [ ] 5
- [ ] There is a tie between multiple categories

In [21]:
def get_category(x):
    if x < 10:
        return "Category 1"
    elif 10 <= x < 20:
        return "Category 2"
    elif 20 <= x < 30:
        return "Category 3"
    elif 30 <= x < 40:
        return "Category 4"
    return "Category 5"

In [22]:
df["CATEGORY"] = df["PRICE"].apply(get_category)

In [23]:
df["CATEGORY"].value_counts()

CATEGORY
Category 3    2028
Category 2    1158
Category 4     503
Category 5     268
Category 1      43
Name: count, dtype: int64

Apply Pre processing
Divide the data into training and test sets

1. Replace the respective missing or unknown values in features room count, riverside and age with np.nan.
2. Keep 30% of the data as test set.
3. Use random_state as 0
4. PRICE is the target, rest of the columns are the features.
5. Apply train test split.

> **Hint**: look for the documentation of the usual function that divides the data into training and test datasets.

### Q12: What is the number of samples in the training set?
- [x] 2800
- [ ] 2900
- [ ] 3000
- [ ] 3100

In [24]:
df["RM"] = df["RM"].replace(-1, np.nan)

In [25]:
df["AGE"] = df["AGE"].replace(-2, np.nan)

In [26]:
df["RIVERSIDE"] = df["RIVERSIDE"].replace("UNKNOWN", np.nan)

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X = df.drop(columns="PRICE")
y = df["PRICE"]

In [29]:
X.head()

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,RIVERSIDE,CATEGORY
0,1.026769,1.429034,7.851300,1.134216,6.0,42.0,5.251911,5,279.201277,20.689586,398.811960,10.461456,NO,Category 3
1,0.848089,0.255543,6.263434,1.245993,7.0,63.0,4.305546,8,307.444529,17.465398,377.153649,11.619690,NO,Category 3
2,10.925905,0.441022,18.322960,2.824833,8.0,NaN,2.409495,25,666.492973,20.351601,387.061355,19.366070,NO,Category 2
3,0.559027,1.041175,11.114920,0.794952,6.0,9.0,6.898669,4,305.514181,19.787314,391.778647,6.206820,NO,Category 3
4,0.905063,81.167963,3.673369,1.029030,8.0,20.0,10.246463,1,315.913960,17.360439,395.833166,10.827105,NO,Category 3

In [30]:
X.shape

(4000, 14)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
X_train.shape, X_test.shape

((2800, 14), (1200, 14))

Apply following preprocessing steps:

1. Drop CATEGORY column
2. CRIM: min max scaling
3. ZN: min max scaling
4. INDUS: standard scaling
5. POLINDEX: min max scaling
6. DIS: min max scaling
7. HIGHWAYCOUNT: min max scaling
8. TAX: min max scaling
9. PTRATIO: min max scaling
10. IMM: min max scaling
11. BPL: min max scaling
12. RM: impute with median then min max scaling
13. AGE: impute with mean then min max scaling
14. RIVERSIDE: Impute with most frequent value then one hot encode.

**NOTE**:
1. Make sure to preprocess the features in exactly above order. Answer of Q.16 depends upon correct order of featuring processing.
2. You may have to use multiple instances of a trasnformer for this question.


### Q13: How many features are there after performing above transformation?
- [x] 14
- [ ] 15
- [ ] 16
- [ ] 17
- [ ] 18

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder

In [33]:
X_train.drop(columns="CATEGORY", inplace=True)
X_test = X_test.drop(columns="CATEGORY")

X_train.head()

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,RIVERSIDE
3336,2.419091,0.463975,9.464205,0.532043,7.0,89.0,2.728780,6,384.198987,21.935086,396.354281,16.238600,NO
2540,0.488829,20.571280,7.478404,1.016154,8.0,NaN,4.586203,4,223.493157,20.379584,391.076562,6.773790,YES
332,6.724792,1.078185,19.284110,2.851655,5.0,100.0,2.233994,24,666.746344,21.520119,375.538011,3.612275,NO
852,4.538359,1.001537,19.932920,1.537855,6.0,99.0,2.007103,6,403.073317,15.048875,263.905771,16.826235,NO
1036,1.417745,1.787572,10.842595,1.000364,9.0,59.0,5.261521,6,304.497433,20.017223,397.560712,13.037207,NO

In [34]:
transformer = ColumnTransformer(
    [
        ("mmscaler", MinMaxScaler(), ["CRIM", "ZN", "POLINDEX", "DIS", "HIGHWAYCOUNT", "TAX", "PTRATIO", "IMM", "BPL"]),
        ("INDUS_stdscaler", StandardScaler(), ["INDUS"]),
        ("RM_pipeline", Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("mm_scaler", MinMaxScaler())
        ]), ["RM"]),
        ("AGE_pipeline", Pipeline([
            ("imputer", SimpleImputer(strategy="mean")),
            ("mm_scaler", MinMaxScaler())
        ]), ["AGE"]),
        ("RIVERSIDE", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder())
        ]), ["RIVERSIDE"])
    ], 
    remainder="passthrough"
)
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('mmscaler', MinMaxScaler(),
                                 ['CRIM', 'ZN', 'POLINDEX', 'DIS',
                                  'HIGHWAYCOUNT', 'TAX', 'PTRATIO', 'IMM',
                                  'BPL']),
                                ('INDUS_stdscaler', StandardScaler(),
                                 ['INDUS']),
                                ('RM_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('mm_scaler',
                                                  MinMaxScaler())]),
                                 ['RM']),
                                ('AGE_pipeline',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('mm_scaler',
                                                  MinMaxScaler())]),
                                 ['AGE']),
                                ('RIVERSIDE',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder', OneHotEncoder())]),
                                 ['RIVERSIDE'])])

In [35]:
X_train = transformer.fit_transform(X_train)
X_test = transformer.transform(X_test)
X_train.shape

(2800, 14)

### Q14: What is the mean of the transformed test data (features only)?
Note : Compute the mean of the whole feature matrix i.e. mean of all values in the transformed test feature matrix

In [36]:
X_test.mean()

0.3861745655097562

### Ref
#### [Sklearn Quick Reference 🔗](https://drive.google.com/file/d/1_yNY2WjFmDRx4X2XdG1qwLFmihLZdWkm/view?usp=sharing)
#### [Dataset 🔗](https://drive.google.com/file/d/1DRtaP8QnU7SFrhMsdR67TBNuq5aOusUe/view?usp=sharing)